name: Deploy to Arweave

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          
      - name: Build site
        run: python3 publish.py
          
      - name: Deploy to Arweave
        run: npx permaweb-deploy --arns-name vitalik-blog --ario-process testnet
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 